slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    map_file_name: ""
    use_sim_time: true
    # L1 相关：
    max_laser_range: 10.0        # 呼应原 carto lua max_range 10.0，过大窄 FOV 易发散
    minimum_travel_distance: 0.1 # 狗晃动大，稍放宽
    minimum_travel_heading: 0.1
    scan_buffer_size: 30
    link_match_minimum_response_fine: 0.1
    loop_search_maximum_distance: 4.0
    do_loop_closing: true
    resolution: 0.05
    max_mapping_time: -1.0
